@startuml

class Project
{
 - name : String
 - gegenstand : List<>
 --
 + addGegenstand
 + removeGegenstand
}

class Gegenstand
{
 - name : String
 - thema : String
 - beschreibung : String
 - alternativen : List<>
 - gruppen : List<>
 - eintritt : Eintritt
 - punkte : Punkte
 - dauer : int
 --
 + addAlternative
 + removeAlternative
 + addGruppe
 + removeGruppe
 + editGruppe
 + addKriterie
 + speichern
 + veroeffentlichen
 + setEintritt
 + setDauer
 + setPunkte
}

enum Eintritt
{
- OFFEN
- EINLADUNG
}

enum Punkte
{
- 3
- 5
}

class Gruppe
{
 - name : String
 - kriterie : List<>
 --
 + addKriterie
 + removeKriterie
}

class Kriterie
{
 - name : String
}


Project -- Gegenstand
Gegenstand -- Gruppe
Gruppe -- Kriterie
Gegenstand - Punkte
Gegenstand - Eintritt


@enduml